# Setup
title: Haya Almutairi
# description
url: https://HayaAlmutairi.github.io
paginate: 5
permalink: pretty
cover_image: /Techb.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: iHayaSM
  card: summary
logo: logo.png
social:
  name: Haya Almutairi
  links:
    - https://twitter.com/iHayaSM
    - https://github.com/HayaAlmutairi
    
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Haya Almutairi
  url: https://github.com/HayaAlmutairi/
  email: ihaya.almutairi@gmail.com
